### ISSUE TITLE
Installation documentation needs to say scipion-em-tomovis should be installed first

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-tomosegmemtv#21]
I tried to install this plugin before installing scipion-em-tomovis which failed because it needs tomovis. The documentation should say somewhere that the plugin should be installed first.

Also, the /bin is not needed in the `unzip DOWNLOADED/FILE -d SCIPION_HOME/software/em/TOMOSEGMEMB_DIRECTORY/tomoSegMemTV/bin/ `since the zipped file comes with a folder bin

**Comment by JorMaister** [comment]
Solved. Tomoviz is in the requirements now.
