### ISSUE TITLE
latest scipion did not find scipion-em-tomosegmemtv

### ISSUE THREAD

**Issue by wsatbluesky** [scipion-em/scipion-em-tomosegmemtv#33]
`
[root@gpu28 ~]# scipion3 installp -p scipion-em-tomosegmemtv
Scipion v3.3.0 - Eugenius
WARNING - The following plugins didn't match available plugin names:
scipion-em-tomosegmemtv
You can see the list of available plugins with the following command:
scipion installp --help
`

**Comment by JorMaister** [comment]
Hi, @wsatbluesky,
Thanks for reporting. It was missing from an internal activation list. Now it is. Please try it again and if the problem persists, let us know.
